#!/usr/bin/env bash

export _JAVA_AWT_WM_NONREPARENTING=1

bspc config border_width 2
bspc config window_gap 0
bspc config split_ratio 0.5
bspc config focused_border_color "#cba6f7"

sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &
ksuperkey -e 'Super_L=Alt_L|F1'
ksuperkey -e 'Super_R=Alt_L|F1'
xsetroot -cursor_name left_ptr
