#!/usr/bin/env bash

export _JAVA_AWT_WM_NONREPARENTING=1

bspc config border_width 2
bspc config window_gap 0
bspc config split_ratio 0.5
bspc config focused_border_color "#cba6f7"

bspc config focus_follows_pointer true
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &
xsetroot -cursor_name left_ptr
